Update nixpkgs.
nixpkgs-unstable updated mbedtls to version 3.
The legacy version is still available as mbedtls_2 though.

This version is required to compile the Ishiiruka Dolphin.
When to trying to compile it using mbedtls 3.3.0 you get the following error:

```
In file included from /build/source/Source/Core/Core/IPC_HLE/WII_Socket.h:57,
                 from /build/source/Source/Core/Core/Core.cpp:59:
/build/source/Source/Core/Core/IPC_HLE/WII_IPC_HLE_Device_net_ssl.h:12:10: fatal error: mbedtls/net.h: No such file or directory
   12 | #include <mbedtls/net.h>
      |          ^~~~~~~~~~~~~~~
```